
var main=new Vue({
    el:".main_right",
    data:{
        show:0,
        item:[],
        items:[
            {   
                item_id:1,
                item_name:"***",
                item_hos:"*****",
                dt:
                [
                    {id:1,hos:"省中医",oid:751,frontNum:12,inNum:98,selectNum:4,testNum:78,overNum:0,falseNum:6,stopNum:6,breakNum:5,boss:"张医生"},
                    {id:2,hos:"佛山中医院",oid:45,frontNum:72,inNum:91,selectNum:15,testNum:11,overNum:2,falseNum:7,stopNum:43,breakNum:6,boss:"李医生"},
                    {id:3,hos:"省中医",oid:71,frontNum:12,inNum:58,selectNum:4,testNum:46,overNum:41,falseNum:0,stopNum:23,breakNum:17,boss:"王院长"},
                ]
            },
            {   
                item_id:2,
                item_name:"***",
                item_hos:"*****",
                dt:
                [
                    {id:1,hos:"***",oid:751,frontNum:12,inNum:98,selectNum:4,testNum:78,overNum:0,falseNum:6,stopNum:6,breakNum:5,boss:"*医生"},
                    {id:2,hos:"****",oid:45,frontNum:72,inNum:91,selectNum:15,testNum:11,overNum:2,falseNum:7,stopNum:43,breakNum:6,boss:"*医生"},
                ]
            },
            {   
                item_id:3,
                item_name:"***",
                item_hos:"*****",
                dt:
                [
                    {id:1,hos:"***",oid:751,frontNum:12,inNum:98,selectNum:4,testNum:78,overNum:0,falseNum:6,stopNum:6,breakNum:5,boss:""},
                    {id:2,hos:"****",oid:45,frontNum:72,inNum:91,selectNum:15,testNum:11,overNum:2,falseNum:7,stopNum:43,breakNum:6,boss:""},
                    {id:3,hos:"***",oid:71,frontNum:12,inNum:58,selectNum:4,testNum:46,overNum:41,falseNum:0,stopNum:23,breakNum:17,boss:""},
                    {id:4,hos:"***",oid:71,frontNum:12,inNum:58,selectNum:4,testNum:46,overNum:41,falseNum:0,stopNum:23,breakNum:17,boss:"*院长"},
                ]
            }
        ],
    },
    methods:{
        nav_detail:function(id){
            for (let index = 0; index < this.items.length; index++) {
                if(id==this.items[index].item_id){
                    console.log(index);
                    this.item=this.items[index].dt;
                    this.show=1;
                    break;
                }
                else{
                    this.show=0;
                }
            }
        }
    }
})